/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerproyecto1;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author yesner
 */
public class frmEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEmpresa
     */
  
    DefaultListModel ModeloNombreA,ModeloTiempo,ModeloArea,ModeloCondicion,ModeloSueldo;
  
    public frmEmpresa() {
        initComponents();
        
       ModeloNombreA = new DefaultListModel();
         ModeloTiempo = new DefaultListModel();
           ModeloArea = new DefaultListModel();
          ModeloCondicion = new DefaultListModel();
        ModeloSueldo = new DefaultListModel();
        
        lstNombreA.setModel(ModeloNombreA);
          lstTiempoS.setModel(ModeloTiempo);
            lstArea.setModel(ModeloArea);
          lstCondicion.setModel(ModeloCondicion);
        LstSueldo.setModel(ModeloSueldo);
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel5 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    txtNombreA = new javax.swing.JTextField();
    txtTiempoS = new javax.swing.JTextField();
    cboArea = new javax.swing.JComboBox<>();
    cboCondicion = new javax.swing.JComboBox<>();
    btnNuevosD = new javax.swing.JButton();
    btnGuardarD = new javax.swing.JButton();
    txtSalario = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    lstTiempoS = new javax.swing.JList<>();
    jScrollPane2 = new javax.swing.JScrollPane();
    lstNombreA = new javax.swing.JList<>();
    jScrollPane3 = new javax.swing.JScrollPane();
    lstCondicion = new javax.swing.JList<>();
    jScrollPane4 = new javax.swing.JScrollPane();
    LstSueldo = new javax.swing.JList<>();
    jScrollPane5 = new javax.swing.JScrollPane();
    lstArea = new javax.swing.JList<>();
    btnMostrar = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jTextField6 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    btnLimpiar = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    btndireccion = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    Exitbtn = new javax.swing.JPanel();
    txtexit = new javax.swing.JLabel();

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jPanel2.setBackground(new java.awt.Color(153, 255, 255));
    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DEL EMPLEADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Academy Engraved LET", 2, 14))); // NOI18N

    txtNombreA.setBackground(new java.awt.Color(204, 255, 255));
    txtNombreA.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    txtNombreA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombres y Apellidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 2, 14))); // NOI18N
    txtNombreA.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNombreAActionPerformed(evt);
      }
    });

    txtTiempoS.setBackground(new java.awt.Color(204, 255, 255));
    txtTiempoS.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    txtTiempoS.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tiempo de Servicio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 2, 14))); // NOI18N

    cboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ayudante", "Conductor", "Laboratorio", "Vigilancia" }));
    cboArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 2, 14))); // NOI18N

    cboCondicion.setBackground(new java.awt.Color(204, 255, 255));
    cboCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contratado", "Fijo", " ", " " }));
    cboCondicion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Condicion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 2, 14))); // NOI18N

    btnNuevosD.setFont(new java.awt.Font("New Peninim MT", 2, 14)); // NOI18N
    btnNuevosD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/photo_2022-12-03 09.18.41.jpeg"))); // NOI18N
    btnNuevosD.setText("Nuevos Datos");
    btnNuevosD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnNuevosD.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNuevosDActionPerformed(evt);
      }
    });

    btnGuardarD.setFont(new java.awt.Font("New Peninim MT", 2, 14)); // NOI18N
    btnGuardarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/grabard.png"))); // NOI18N
    btnGuardarD.setText("Grabar Datos");
    btnGuardarD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnGuardarD.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarDActionPerformed(evt);
      }
    });

    txtSalario.setBackground(new java.awt.Color(204, 255, 255));
    txtSalario.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    txtSalario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Salario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 2, 14))); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTiempoS, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(txtNombreA)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cboCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(btnGuardarD)
            .addGap(48, 48, 48)
            .addComponent(btnNuevosD, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtTiempoS)
          .addComponent(txtSalario))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cboCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGuardarD)
          .addComponent(btnNuevosD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 9, Short.MAX_VALUE))
    );

    lstTiempoS.setBackground(new java.awt.Color(204, 255, 255));
    lstTiempoS.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Años Ser.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Academy Engraved LET", 2, 14))); // NOI18N
    lstTiempoS.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    jScrollPane1.setViewportView(lstTiempoS);

    lstNombreA.setBackground(new java.awt.Color(204, 255, 255));
    lstNombreA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nombres y Apellidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Academy Engraved LET", 2, 14))); // NOI18N
    lstNombreA.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    lstNombreA.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { " " };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane2.setViewportView(lstNombreA);

    lstCondicion.setBackground(new java.awt.Color(204, 255, 255));
    lstCondicion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Condicion"), "Condicion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Academy Engraved LET", 2, 14))); // NOI18N
    lstCondicion.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    jScrollPane3.setViewportView(lstCondicion);

    LstSueldo.setBackground(new java.awt.Color(204, 255, 255));
    LstSueldo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sueldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Academy Engraved LET", 2, 14))); // NOI18N
    LstSueldo.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    jScrollPane4.setViewportView(LstSueldo);

    lstArea.setBackground(new java.awt.Color(204, 255, 255));
    lstArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Academy Engraved LET", 2, 14))); // NOI18N
    lstArea.setFont(new java.awt.Font("American Typewriter", 2, 14)); // NOI18N
    jScrollPane5.setViewportView(lstArea);

    btnMostrar.setBackground(new java.awt.Color(153, 255, 255));
    btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/mostar.png"))); // NOI18N
    btnMostrar.setText("  Mostrar");
    btnMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jPanel3.setBackground(new java.awt.Color(153, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen De Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("American Typewriter", 2, 14))); // NOI18N

    jTextField1.setBackground(new java.awt.Color(204, 255, 255));
    jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "A"));

    jTextField2.setBackground(new java.awt.Color(204, 255, 255));
    jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "B"));

    jTextField5.setBackground(new java.awt.Color(204, 255, 255));
    jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "D"));

    jTextField6.setBackground(new java.awt.Color(204, 255, 255));
    jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "C"));

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
          .addComponent(jTextField6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
          .addComponent(jTextField2))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTextField2)
          .addComponent(jTextField1))
        .addGap(18, 18, 18)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
          .addComponent(jTextField6))
        .addGap(9, 9, 9))
    );

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/empresa.png"))); // NOI18N
    jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Empresa"));

    btnLimpiar.setBackground(new java.awt.Color(153, 255, 255));
    btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/elimar.png"))); // NOI18N
    btnLimpiar.setText(" Limpiar");
    btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jPanel4.setBackground(new java.awt.Color(153, 255, 255));
    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefonos y Correo electronico"));

    btndireccion.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
    btndireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/dir.png"))); // NOI18N
    btndireccion.setText(" Dirección");
    btndireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btndireccion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btndireccionActionPerformed(evt);
      }
    });

    jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/Phone_30029.png"))); // NOI18N
    jButton1.setText("Telefono");
    jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/com/corre.png"))); // NOI18N
    jButton2.setText("Correo");
    jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btndireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btndireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));

    Exitbtn.setBackground(new java.awt.Color(255, 255, 255));
    Exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        ExitbtnMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        ExitbtnMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        ExitbtnMouseExited(evt);
      }
    });

    txtexit.setText("X");

    javax.swing.GroupLayout ExitbtnLayout = new javax.swing.GroupLayout(Exitbtn);
    Exitbtn.setLayout(ExitbtnLayout);
    ExitbtnLayout.setHorizontalGroup(
      ExitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ExitbtnLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtexit)
        .addContainerGap(12, Short.MAX_VALUE))
    );
    ExitbtnLayout.setVerticalGroup(
      ExitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel6Layout.createSequentialGroup()
        .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(305, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(8, 8, 8))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
 
  private void btnGuardarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDActionPerformed
    String NombreA = txtNombreA.getText();
    double Servicio = Double.parseDouble(txtTiempoS.getText());
    String Area = cboArea.getSelectedItem().toString();
    String Condicion = cboCondicion.getSelectedItem().toString();
    double Salario = Double.parseDouble(txtSalario.getText());
    ModeloNombreA.addElement(NombreA);
    ModeloTiempo.addElement(Servicio);
    ModeloArea.addElement(Area);
    ModeloCondicion.addElement(Condicion);
    ModeloSueldo.addElement(Salario);
    txtNombreA.setText("");
    txtTiempoS.setText("");
    txtSalario.setText("");
    cboArea.setSelectedIndex(-1);
    cboCondicion.setSelectedIndex(-1);
    txtNombreA.requestFocus();
  }//GEN-LAST:event_btnGuardarDActionPerformed

  private void txtNombreAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNombreAActionPerformed

  private void btnNuevosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosDActionPerformed
  DefaultListModel modelo = (DefaultListModel) lstNombreA.getModel();
    modelo.removeAllElements();
        
    DefaultListModel modelo2 = (DefaultListModel) lstTiempoS.getModel();
      modelo2.removeAllElements();
        
      DefaultListModel modelo3 = (DefaultListModel) lstArea.getModel();
        modelo3.removeAllElements();
        
        DefaultListModel modelo4 = (DefaultListModel) lstCondicion.getModel();
          modelo4.removeAllElements();
        
          DefaultListModel modelo5 = (DefaultListModel) LstSueldo.getModel();
            modelo5.removeAllElements();
          
  }//GEN-LAST:event_btnNuevosDActionPerformed

  private void ExitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseClicked
     System.exit(0);    
  }//GEN-LAST:event_ExitbtnMouseClicked

  private void ExitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseEntered
        Exitbtn.setBackground(Color.red);
        txtexit.setForeground(Color.white);
  }//GEN-LAST:event_ExitbtnMouseEntered

  private void ExitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseExited
        Exitbtn.setBackground(Color.white);
        txtexit.setForeground(Color.black);
  }//GEN-LAST:event_ExitbtnMouseExited

  private void btndireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndireccionActionPerformed
    JOptionPane.showMessageDialog(null, "Kilometro 186 Carretera San Carlos");
  }//GEN-LAST:event_btndireccionActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JOptionPane.showMessageDialog(null, "Llamar al : 86345690");
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    JOptionPane.showMessageDialog(null, "Elmilagro.@gmail.com");
  }//GEN-LAST:event_jButton2ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Exitbtn;
  private javax.swing.JList<String> LstSueldo;
  private javax.swing.JButton btnGuardarD;
  private javax.swing.JButton btnLimpiar;
  private javax.swing.JButton btnMostrar;
  private javax.swing.JButton btnNuevosD;
  private javax.swing.JButton btndireccion;
  private javax.swing.JComboBox<String> cboArea;
  private javax.swing.JComboBox<String> cboCondicion;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JList<String> lstArea;
  private javax.swing.JList<String> lstCondicion;
  private javax.swing.JList<String> lstNombreA;
  private javax.swing.JList<String> lstTiempoS;
  private javax.swing.JTextField txtNombreA;
  private javax.swing.JTextField txtSalario;
  private javax.swing.JTextField txtTiempoS;
  private javax.swing.JLabel txtexit;
  // End of variables declaration//GEN-END:variables
}
